# Mock data for Saturday Planner
# Real place names + realistic details to make suggestions feel genuine
# TODO: Replace with actual API calls (Google Places, Zomato) for production

ACTIVITIES = {
    "bangalore": [
        {
            "name": "Morning Walk at Cubbon Park",
            "type": "walk",
            "cost": 0,
            "duration_hours": 1.5,
            "mood_tags": ["relaxed", "tired", "peaceful"],
            "interest_tags": ["walks", "nature", "photography"],
            "crowd_level": "low",
            "time_of_day": "morning",
            "description": "Beautiful green park in the heart of the city. Great for a quiet morning stroll with old trees and minimal crowds early on."
        },
        {
            "name": "Live Music at The Humming Tree",
            "type": "music",
            "cost": 500,
            "duration_hours": 2,
            "mood_tags": ["energetic", "adventurous", "social"],
            "interest_tags": ["music", "nightlife"],
            "crowd_level": "medium",
            "time_of_day": "evening",
            "description": "Popular indie music venue in Indiranagar. Check for weekend gigs — usually has great local bands."
        },
        {
            "name": "Art Walk at Bangalore Palace Grounds",
            "type": "art",
            "cost": 250,
            "duration_hours": 1.5,
            "mood_tags": ["relaxed", "curious", "creative"],
            "interest_tags": ["art", "culture", "photography"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Explore street art and exhibitions around the palace area. Good vibes, usually not too crowded on weekends."
        },
        {
            "name": "Cycling at Lalbagh Botanical Garden",
            "type": "outdoor",
            "cost": 100,
            "duration_hours": 2,
            "mood_tags": ["energetic", "adventurous"],
            "interest_tags": ["fitness", "nature", "walks"],
            "crowd_level": "medium",
            "time_of_day": "morning",
            "description": "Rent a cycle and ride through one of Bangalore's most iconic gardens. The glasshouse and lake are must-sees."
        },
        {
            "name": "Board Games at Dice n Dine",
            "type": "indoor",
            "cost": 400,
            "duration_hours": 2,
            "mood_tags": ["relaxed", "social", "tired"],
            "interest_tags": ["games", "indoor", "social"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Cozy board game café in Koramangala. Great if you want to chill without too much effort."
        },
        {
            "name": "Book Browsing at Blossom Book House",
            "type": "shopping",
            "cost": 300,
            "duration_hours": 1,
            "mood_tags": ["relaxed", "curious", "tired", "peaceful"],
            "interest_tags": ["books", "shopping", "culture"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Iconic second-hand bookstore on Church Street. You can spend hours here and walk out with a stack for cheap."
        },
        {
            "name": "Sunset at Nandi Hills",
            "type": "outdoor",
            "cost": 200,
            "duration_hours": 4,
            "mood_tags": ["adventurous", "energetic", "romantic"],
            "interest_tags": ["nature", "photography", "drives"],
            "crowd_level": "high",
            "time_of_day": "morning",
            "description": "About 60km from the city. Best for sunrise but sunset works too. Can get crowded on weekends though."
        },
        {
            "name": "Pottery Workshop at Clay Station",
            "type": "workshop",
            "cost": 800,
            "duration_hours": 2,
            "mood_tags": ["creative", "relaxed", "curious"],
            "interest_tags": ["art", "workshops", "creative"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Try your hand at pottery. Fun weekend activity, and you get to keep what you make."
        },
        {
            "name": "Street Food Tour at VV Puram",
            "type": "food_walk",
            "cost": 300,
            "duration_hours": 1.5,
            "mood_tags": ["adventurous", "social", "energetic"],
            "interest_tags": ["food", "walks", "culture"],
            "crowd_level": "high",
            "time_of_day": "evening",
            "description": "Famous food street with dozens of stalls. Best visited in the evening. Try the dosas, chaat, and holige."
        },
        {
            "name": "Coffee Tasting at Third Wave Coffee",
            "type": "cafe",
            "cost": 350,
            "duration_hours": 1,
            "mood_tags": ["relaxed", "tired", "peaceful"],
            "interest_tags": ["food", "coffee", "indoor"],
            "crowd_level": "low",
            "time_of_day": "morning",
            "description": "Great specialty coffee in a chill setting. Perfect for a slow start to the day."
        },
    ],
    "delhi": [
        {
            "name": "Walk around Lodhi Garden",
            "type": "walk",
            "cost": 0,
            "duration_hours": 1.5,
            "mood_tags": ["relaxed", "tired", "peaceful"],
            "interest_tags": ["walks", "nature", "photography", "history"],
            "crowd_level": "low",
            "time_of_day": "morning",
            "description": "Beautiful historic garden with 15th-century tombs. Quiet in the mornings, perfect for a peaceful walk."
        },
        {
            "name": "Street Food at Chandni Chowk",
            "type": "food_walk",
            "cost": 400,
            "duration_hours": 2,
            "mood_tags": ["adventurous", "energetic", "social"],
            "interest_tags": ["food", "culture", "walks", "shopping"],
            "crowd_level": "high",
            "time_of_day": "afternoon",
            "description": "Old Delhi's famous food street. Paranthas at Paranthe Wali Gali, jalebis at Old Famous, and much more."
        },
        {
            "name": "Explore Hauz Khas Village",
            "type": "culture",
            "cost": 200,
            "duration_hours": 2,
            "mood_tags": ["curious", "social", "creative"],
            "interest_tags": ["art", "culture", "shopping", "photography"],
            "crowd_level": "medium",
            "time_of_day": "afternoon",
            "description": "Artsy neighborhood with galleries, boutiques, and a gorgeous lake. Great for an afternoon wander."
        },
        {
            "name": "Live Music at Piano Man Jazz Club",
            "type": "music",
            "cost": 600,
            "duration_hours": 2.5,
            "mood_tags": ["relaxed", "social", "creative"],
            "interest_tags": ["music", "nightlife"],
            "crowd_level": "medium",
            "time_of_day": "evening",
            "description": "Best jazz venue in Delhi. Saturday evenings usually have great lineups. Intimate setting."
        },
        {
            "name": "Cycling at Kartavya Path",
            "type": "outdoor",
            "cost": 150,
            "duration_hours": 1.5,
            "mood_tags": ["energetic", "adventurous"],
            "interest_tags": ["fitness", "walks", "nature"],
            "crowd_level": "low",
            "time_of_day": "morning",
            "description": "Early morning cycling along the iconic boulevard. Rent bikes nearby and enjoy the open road."
        },
        {
            "name": "Book Cafe at Kunzum Travel Cafe",
            "type": "cafe",
            "cost": 0,
            "duration_hours": 1.5,
            "mood_tags": ["relaxed", "tired", "curious"],
            "interest_tags": ["books", "coffee", "indoor"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Pay-what-you-like cafe in HKV. Great collection of travel books and a chill vibe."
        },
        {
            "name": "National Gallery of Modern Art",
            "type": "art",
            "cost": 150,
            "duration_hours": 2,
            "mood_tags": ["curious", "relaxed", "creative"],
            "interest_tags": ["art", "culture", "photography"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Impressive collection of Indian modern art. Air-conditioned and peaceful — good escape from Delhi heat."
        },
        {
            "name": "Evening at Dilli Haat",
            "type": "shopping",
            "cost": 300,
            "duration_hours": 2,
            "mood_tags": ["social", "curious", "adventurous"],
            "interest_tags": ["shopping", "food", "culture"],
            "crowd_level": "medium",
            "time_of_day": "evening",
            "description": "Open-air market with crafts and food from different states. Entry fee is minimal, great finds."
        },
    ],
    "mumbai": [
        {
            "name": "Morning Walk at Marine Drive",
            "type": "walk",
            "cost": 0,
            "duration_hours": 1,
            "mood_tags": ["relaxed", "tired", "peaceful", "romantic"],
            "interest_tags": ["walks", "nature", "photography"],
            "crowd_level": "low",
            "time_of_day": "morning",
            "description": "The Queen's Necklace. Early morning here hits different — sea breeze, quiet roads, beautiful coastline."
        },
        {
            "name": "Street Art Walk at Sassoon Docks",
            "type": "art",
            "cost": 0,
            "duration_hours": 1.5,
            "mood_tags": ["curious", "creative", "adventurous"],
            "interest_tags": ["art", "photography", "culture"],
            "crowd_level": "low",
            "time_of_day": "morning",
            "description": "During the annual art fest the docks transform with installations. Even outside the fest, the area has character."
        },
        {
            "name": "Explore Colaba Causeway",
            "type": "shopping",
            "cost": 500,
            "duration_hours": 2,
            "mood_tags": ["social", "adventurous", "energetic"],
            "interest_tags": ["shopping", "food", "walks"],
            "crowd_level": "high",
            "time_of_day": "afternoon",
            "description": "Iconic street shopping stretch. Bargain for clothes, accessories, antiques. Cafes all around too."
        },
        {
            "name": "Cutting Chai at Girgaon Chowpatty",
            "type": "cafe",
            "cost": 50,
            "duration_hours": 0.5,
            "mood_tags": ["relaxed", "tired", "peaceful"],
            "interest_tags": ["food", "culture"],
            "crowd_level": "low",
            "time_of_day": "evening",
            "description": "Nothing beats a cutting chai watching the sunset by the sea. Simple pleasure, pure Mumbai."
        },
        {
            "name": "Live Music at AntiSocial",
            "type": "music",
            "cost": 700,
            "duration_hours": 2.5,
            "mood_tags": ["energetic", "social", "creative"],
            "interest_tags": ["music", "nightlife"],
            "crowd_level": "medium",
            "time_of_day": "evening",
            "description": "Usually indie/electronic gigs on Saturday nights. Good sound, good crowd."
        },
        {
            "name": "Bandstand Promenade Walk",
            "type": "walk",
            "cost": 0,
            "duration_hours": 1.5,
            "mood_tags": ["relaxed", "romantic", "peaceful"],
            "interest_tags": ["walks", "nature", "photography"],
            "crowd_level": "medium",
            "time_of_day": "evening",
            "description": "Bandra's iconic promenade. Sea-facing, breezy, great for evening strolls. Sea Link views are a bonus."
        },
        {
            "name": "Food Trail at Mohammad Ali Road",
            "type": "food_walk",
            "cost": 400,
            "duration_hours": 1.5,
            "mood_tags": ["adventurous", "social", "energetic"],
            "interest_tags": ["food", "culture", "walks"],
            "crowd_level": "high",
            "time_of_day": "evening",
            "description": "Famous for kebabs, biryanis, and desserts. Best in the evening. Come hungry."
        },
    ],
    "gurgaon": [
        {
            "name": "Walk at Aravalli Biodiversity Park",
            "type": "walk",
            "cost": 0,
            "duration_hours": 1.5,
            "mood_tags": ["relaxed", "tired", "peaceful"],
            "interest_tags": ["walks", "nature", "fitness"],
            "crowd_level": "low",
            "time_of_day": "morning",
            "description": "Surprisingly green and peaceful for Gurgaon. Good trails, birds, a break from the concrete jungle."
        },
        {
            "name": "Board Games at The Game Palate",
            "type": "indoor",
            "cost": 450,
            "duration_hours": 2,
            "mood_tags": ["relaxed", "social", "tired"],
            "interest_tags": ["games", "indoor", "social"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Board game café with a huge collection. Good food too. Perfect lazy Saturday plan."
        },
        {
            "name": "Café Hopping at Cyber Hub",
            "type": "cafe",
            "cost": 600,
            "duration_hours": 2,
            "mood_tags": ["social", "relaxed", "curious"],
            "interest_tags": ["food", "coffee", "social"],
            "crowd_level": "medium",
            "time_of_day": "afternoon",
            "description": "Plenty of good cafes and restaurants. People's Company, Imperfecto, or just grab coffee and people-watch."
        },
        {
            "name": "Shopping at Galleria Market",
            "type": "shopping",
            "cost": 500,
            "duration_hours": 1.5,
            "mood_tags": ["social", "energetic"],
            "interest_tags": ["shopping", "food"],
            "crowd_level": "medium",
            "time_of_day": "afternoon",
            "description": "DLF Galleria has a mix of brands and local stores. Good for a casual shopping spree."
        },
        {
            "name": "Sunset Drive to Damdama Lake",
            "type": "outdoor",
            "cost": 300,
            "duration_hours": 3,
            "mood_tags": ["adventurous", "romantic", "energetic"],
            "interest_tags": ["nature", "drives", "photography"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "About 45 min drive. Nice lake, boating options, great for unwinding away from the city."
        },
        {
            "name": "Live Music at Sector 29",
            "type": "music",
            "cost": 500,
            "duration_hours": 2,
            "mood_tags": ["energetic", "social"],
            "interest_tags": ["music", "nightlife", "food"],
            "crowd_level": "high",
            "time_of_day": "evening",
            "description": "Multiple bars with live music on weekends. Walk around till you find a vibe you like."
        },
    ],
    "hyderabad": [
        {
            "name": "Walk around Hussain Sagar Lake",
            "type": "walk",
            "cost": 0,
            "duration_hours": 1.5,
            "mood_tags": ["relaxed", "tired", "peaceful"],
            "interest_tags": ["walks", "nature", "photography"],
            "crowd_level": "medium",
            "time_of_day": "morning",
            "description": "Lakeside walk with views of the Buddha statue. Nice and breezy in the mornings."
        },
        {
            "name": "Biryani Trail at Paradise & Bawarchi",
            "type": "food_walk",
            "cost": 500,
            "duration_hours": 1.5,
            "mood_tags": ["adventurous", "social"],
            "interest_tags": ["food", "culture"],
            "crowd_level": "high",
            "time_of_day": "afternoon",
            "description": "Can't visit Hyderabad without biryani. Hit up the iconic spots and compare."
        },
        {
            "name": "Evening at Charminar & Laad Bazaar",
            "type": "culture",
            "cost": 300,
            "duration_hours": 2,
            "mood_tags": ["curious", "adventurous", "social"],
            "interest_tags": ["culture", "shopping", "photography", "walks"],
            "crowd_level": "high",
            "time_of_day": "evening",
            "description": "Iconic monument + bustling bazaar for bangles and street food. Best in the evening with the lights."
        },
        {
            "name": "Café hopping in Jubilee Hills",
            "type": "cafe",
            "cost": 400,
            "duration_hours": 1.5,
            "mood_tags": ["relaxed", "social", "tired"],
            "interest_tags": ["food", "coffee", "indoor"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Tons of good cafes in the area. Roastery Coffee House and Autumn Leaf are great picks."
        },
    ],
    "pune": [
        {
            "name": "Trek to Sinhagad Fort",
            "type": "outdoor",
            "cost": 100,
            "duration_hours": 4,
            "mood_tags": ["energetic", "adventurous"],
            "interest_tags": ["fitness", "nature", "walks", "photography"],
            "crowd_level": "medium",
            "time_of_day": "morning",
            "description": "Classic Pune weekend trek. About 35km from city. Moderate difficulty, great views, pithla-bhakri at the top."
        },
        {
            "name": "Café Hopping at FC Road / Koregaon Park",
            "type": "cafe",
            "cost": 400,
            "duration_hours": 2,
            "mood_tags": ["relaxed", "social", "curious"],
            "interest_tags": ["food", "coffee", "indoor"],
            "crowd_level": "medium",
            "time_of_day": "afternoon",
            "description": "Pune's café culture is underrated. Vohuman Café for breakfast, newer spots in KP for later."
        },
        {
            "name": "Explore Aga Khan Palace",
            "type": "culture",
            "cost": 100,
            "duration_hours": 1.5,
            "mood_tags": ["curious", "relaxed", "peaceful"],
            "interest_tags": ["history", "culture", "photography", "walks"],
            "crowd_level": "low",
            "time_of_day": "afternoon",
            "description": "Beautiful palace with Gandhiji's memorial. Peaceful gardens and lots of history."
        },
        {
            "name": "Live Music at Hard Rock Cafe",
            "type": "music",
            "cost": 800,
            "duration_hours": 2.5,
            "mood_tags": ["energetic", "social"],
            "interest_tags": ["music", "nightlife", "food"],
            "crowd_level": "medium",
            "time_of_day": "evening",
            "description": "Reliable option for Saturday night live music. Usually cover bands or local acts."
        },
    ],
}

FOOD_SPOTS = {
    "bangalore": [
        {
            "name": "Vidyarthi Bhavan",
            "cuisine": "South Indian",
            "cost_per_person": 150,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "high",
            "area": "Basavanagudi",
            "description": "Legendary dosa spot since 1943. The butter masala dosa is iconic. Expect a queue.",
            "rating": 4.5,
        },
        {
            "name": "Truffles",
            "cuisine": "Continental",
            "cost_per_person": 450,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "high",
            "area": "Koramangala",
            "description": "Bangalore's favourite burger and steak place. Always packed, always worth the wait.",
            "rating": 4.3,
        },
        {
            "name": "Brahmin's Coffee Bar",
            "cuisine": "South Indian",
            "cost_per_person": 80,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "medium",
            "area": "Shankarapura",
            "description": "No-frills idli-vada-coffee experience. Standing-only. Pure Bangalore tradition.",
            "rating": 4.6,
        },
        {
            "name": "The Permit Room",
            "cuisine": "South Indian (Modern)",
            "cost_per_person": 600,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "dinner",
            "crowd_level": "medium",
            "area": "Lavelle Road",
            "description": "Modern South Indian with cocktails. Great for a slightly fancy dinner without being stiff.",
            "rating": 4.2,
        },
        {
            "name": "Veena Stores",
            "cuisine": "South Indian",
            "cost_per_person": 60,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "high",
            "area": "Malleshwaram",
            "description": "Iconic neighborhood breakfast spot. Khara bath and kesari bath combo is a must-try.",
            "rating": 4.4,
        },
        {
            "name": "Nagarjuna",
            "cuisine": "Andhra",
            "cost_per_person": 350,
            "dietary": ["non-vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "high",
            "area": "Residency Road",
            "description": "Best Andhra meals in Bangalore. Fiery biryani and unlimited thali.",
            "rating": 4.4,
        },
        {
            "name": "CTR (Central Tiffin Room)",
            "cuisine": "South Indian",
            "cost_per_person": 120,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "high",
            "area": "Malleshwaram",
            "description": "Benne masala dosa worth the 30-min wait. Crispy, buttery perfection.",
            "rating": 4.5,
        },
    ],
    "delhi": [
        {
            "name": "Paranthe Wali Gali",
            "cuisine": "North Indian Street Food",
            "cost_per_person": 200,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "high",
            "area": "Chandni Chowk",
            "description": "Historic alley famous for deep-fried paranthas with various stuffings. Pure indulgence.",
            "rating": 4.2,
        },
        {
            "name": "Karim's",
            "cuisine": "Mughlai",
            "cost_per_person": 400,
            "dietary": ["non-vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "high",
            "area": "Jama Masjid",
            "description": "Since 1913. Mutton burra and seekh kebabs are legendary. Delhi food royalty.",
            "rating": 4.5,
        },
        {
            "name": "Saravana Bhavan",
            "cuisine": "South Indian",
            "cost_per_person": 250,
            "dietary": ["vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "medium",
            "area": "Connaught Place",
            "description": "Reliable South Indian chain. Great thalis and filter coffee. Clean and consistent.",
            "rating": 4.1,
        },
        {
            "name": "Big Chill",
            "cuisine": "Italian / Continental",
            "cost_per_person": 700,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "dinner",
            "crowd_level": "high",
            "area": "Khan Market",
            "description": "Delhi institution for pasta and cakes. Always has a waitlist on weekends.",
            "rating": 4.3,
        },
        {
            "name": "Andhra Bhawan Canteen",
            "cuisine": "Andhra",
            "cost_per_person": 150,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "high",
            "area": "Feroze Shah Road",
            "description": "Government canteen with insane unlimited thali. ₹150 for a feast. Queue forms early.",
            "rating": 4.6,
        },
        {
            "name": "Café Lota",
            "cuisine": "Modern Indian",
            "cost_per_person": 500,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "medium",
            "area": "Pragati Maidan",
            "description": "Inside the Crafts Museum. Beautiful setting, inventive menu. Rabri french toast is famous.",
            "rating": 4.4,
        },
    ],
    "mumbai": [
        {
            "name": "Ram Ashray",
            "cuisine": "South Indian",
            "cost_per_person": 100,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "medium",
            "area": "Matunga",
            "description": "Old-school Udupi restaurant. Fluffy idlis and strong filter coffee. All flavour.",
            "rating": 4.3,
        },
        {
            "name": "Leopold Cafe",
            "cuisine": "Multi-cuisine",
            "cost_per_person": 550,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "high",
            "area": "Colaba",
            "description": "Iconic Mumbai cafe since 1871. Touristy but the vibe is unmatched.",
            "rating": 4.0,
        },
        {
            "name": "Swati Snacks",
            "cuisine": "Gujarati Street Food",
            "cost_per_person": 300,
            "dietary": ["vegetarian"],
            "meal_type": "snacks",
            "crowd_level": "high",
            "area": "Tardeo",
            "description": "Mumbai's best chaat and Gujarati snacks. Panki and dahi puri are exceptional.",
            "rating": 4.5,
        },
        {
            "name": "Trishna",
            "cuisine": "Seafood",
            "cost_per_person": 800,
            "dietary": ["non-vegetarian"],
            "meal_type": "dinner",
            "crowd_level": "medium",
            "area": "Fort",
            "description": "Famous for butter garlic crab. Premium seafood in a no-nonsense setting.",
            "rating": 4.4,
        },
        {
            "name": "Cafe Madras",
            "cuisine": "South Indian",
            "cost_per_person": 120,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "medium",
            "area": "Matunga",
            "description": "Perfect filter coffee and crisp dosas. A Matunga institution.",
            "rating": 4.4,
        },
    ],
    "gurgaon": [
        {
            "name": "SodaBottleOpenerWala",
            "cuisine": "Parsi / Irani",
            "cost_per_person": 500,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "medium",
            "area": "Cyber Hub",
            "description": "Fun Parsi-themed restaurant. Berry pulao and Irani chai are highlights.",
            "rating": 4.2,
        },
        {
            "name": "Burma Burma",
            "cuisine": "Burmese",
            "cost_per_person": 600,
            "dietary": ["vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "medium",
            "area": "Cyber Hub",
            "description": "All-vegetarian Burmese food. Unique flavours. The oh-no khao suey is a must.",
            "rating": 4.4,
        },
        {
            "name": "Old Town Cafe",
            "cuisine": "North Indian / Cafe",
            "cost_per_person": 350,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "low",
            "area": "Sector 29",
            "description": "Charming cafe with good breakfast options. Eggs, parathas, strong coffee.",
            "rating": 4.0,
        },
        {
            "name": "Bikanervala",
            "cuisine": "North Indian / Sweets",
            "cost_per_person": 200,
            "dietary": ["vegetarian"],
            "meal_type": "snacks",
            "crowd_level": "medium",
            "area": "Multiple locations",
            "description": "Reliable chain for sweets, chaat, and thalis. Nothing fancy, consistently good.",
            "rating": 4.0,
        },
    ],
    "hyderabad": [
        {
            "name": "Paradise Biryani",
            "cuisine": "Hyderabadi",
            "cost_per_person": 300,
            "dietary": ["non-vegetarian"],
            "meal_type": "lunch",
            "crowd_level": "high",
            "area": "Multiple locations",
            "description": "The OG Hyderabadi biryani. Touristy? Yes. Still worth it? Absolutely.",
            "rating": 4.3,
        },
        {
            "name": "Chutneys",
            "cuisine": "South Indian",
            "cost_per_person": 200,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "medium",
            "area": "Banjara Hills",
            "description": "Best dosas and pesarattu in Hyderabad. Breakfast here is a weekend ritual.",
            "rating": 4.5,
        },
        {
            "name": "Nimrah Café",
            "cuisine": "Irani Cafe",
            "cost_per_person": 80,
            "dietary": ["vegetarian"],
            "meal_type": "snacks",
            "crowd_level": "medium",
            "area": "Charminar",
            "description": "Iconic Irani chai and Osmania biscuits right next to Charminar. Cheap and unforgettable.",
            "rating": 4.4,
        },
    ],
    "pune": [
        {
            "name": "Vohuman Café",
            "cuisine": "Irani Cafe",
            "cost_per_person": 100,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "high",
            "area": "Sassoon Road",
            "description": "Pune institution. Bun maska + chai is the classic combo. Cash only.",
            "rating": 4.3,
        },
        {
            "name": "Vaishali",
            "cuisine": "South Indian",
            "cost_per_person": 200,
            "dietary": ["vegetarian"],
            "meal_type": "breakfast",
            "crowd_level": "high",
            "area": "FC Road",
            "description": "Iconic for South Indian breakfast. Students, families, everyone comes here weekends.",
            "rating": 4.2,
        },
        {
            "name": "Malaka Spice",
            "cuisine": "Asian Fusion",
            "cost_per_person": 550,
            "dietary": ["vegetarian", "non-vegetarian"],
            "meal_type": "dinner",
            "crowd_level": "medium",
            "area": "Koregaon Park",
            "description": "Beautiful garden setting with great Asian food. Perfect for a relaxed dinner.",
            "rating": 4.3,
        },
        {
            "name": "Chitale Bandhu",
            "cuisine": "Maharashtrian Sweets",
            "cost_per_person": 150,
            "dietary": ["vegetarian"],
            "meal_type": "snacks",
            "crowd_level": "medium",
            "area": "Multiple locations",
            "description": "Famous bakarwadi and sweets. Pick some up — it's practically mandatory.",
            "rating": 4.5,
        },
    ],
}

# Generic fallback for unsupported cities
DEFAULT_ACTIVITIES = [
    {
        "name": "Morning walk in a local park",
        "type": "walk",
        "cost": 0,
        "duration_hours": 1,
        "mood_tags": ["relaxed", "tired", "peaceful"],
        "interest_tags": ["walks", "nature"],
        "crowd_level": "low",
        "time_of_day": "morning",
        "description": "Find the nearest green space and take a leisurely walk. Simple but always works."
    },
    {
        "name": "Visit a local café",
        "type": "cafe",
        "cost": 300,
        "duration_hours": 1.5,
        "mood_tags": ["relaxed", "tired", "social"],
        "interest_tags": ["food", "coffee", "books"],
        "crowd_level": "low",
        "time_of_day": "morning",
        "description": "Find a well-reviewed café nearby. Coffee, maybe a book, and just chill."
    },
    {
        "name": "Explore a local market",
        "type": "shopping",
        "cost": 500,
        "duration_hours": 2,
        "mood_tags": ["curious", "social", "adventurous"],
        "interest_tags": ["shopping", "food", "culture"],
        "crowd_level": "medium",
        "time_of_day": "afternoon",
        "description": "Every city has a local market worth exploring. Street food, bargains, people-watching."
    },
    {
        "name": "Watch a movie",
        "type": "entertainment",
        "cost": 400,
        "duration_hours": 3,
        "mood_tags": ["tired", "relaxed", "social"],
        "interest_tags": ["movies", "entertainment", "indoor"],
        "crowd_level": "medium",
        "time_of_day": "afternoon",
        "description": "Sometimes the perfect Saturday is just a good movie with popcorn. No shame in that."
    },
    {
        "name": "Cook something new at home",
        "type": "indoor",
        "cost": 300,
        "duration_hours": 2,
        "mood_tags": ["creative", "relaxed", "tired"],
        "interest_tags": ["food", "creative", "indoor"],
        "crowd_level": "low",
        "time_of_day": "afternoon",
        "description": "Pick a recipe you've never tried. Music on, cook, enjoy. Low-effort, high-reward."
    },
]

DEFAULT_FOOD = [
    {
        "name": "Local popular restaurant (check Google Maps)",
        "cuisine": "Varies",
        "cost_per_person": 400,
        "dietary": ["vegetarian", "non-vegetarian"],
        "meal_type": "lunch",
        "crowd_level": "medium",
        "area": "City center",
        "description": "Search for top-rated places nearby. Sort by rating, pick something that fits your mood.",
        "rating": 4.0,
    },
    {
        "name": "Street food stalls",
        "cuisine": "Street Food",
        "cost_per_person": 150,
        "dietary": ["vegetarian"],
        "meal_type": "snacks",
        "crowd_level": "medium",
        "area": "Local market area",
        "description": "Every city has great street food. Ask a local or check Google Maps for food streets.",
        "rating": 4.0,
    },
]

# City aliases — handles common variations
CITY_ALIASES = {
    "bengaluru": "bangalore",
    "blr": "bangalore",
    "new delhi": "delhi",
    "ncr": "delhi",
    "noida": "delhi",
    "bombay": "mumbai",
    "gurugram": "gurgaon",
    "ggn": "gurgaon",
}
